Get http://localhost:3000/products/
Content-Type: application/json
#works #index


###

POST http://localhost:3000/products
Content-Type: application/json
#works #create 

{
  "name": "Soup",
  "price": "4",
  "ingredients": "Ask about soup of the day."
}

#works


###

GET http://localhost:3000/products/1
Content-Type: application/json
#works (product by id) show


###

PATCH http://localhost:3000/products/1
Content-Type: application/json

 {
   "image_url": "https://upload.wikimedia.org/wikipedia/commons/4/47/Hamburger_%28black_bg%29.jpg"
 }

#works(update) 

###

DELETE http://localhost:3000/products/2
Content-Type: application/json
#works #destroy



#### Begin supplier requests

#create
POST http://localhost:3000/suppliers
Content-Type: application/json

{

  "name": "Pepsi",
  "email": "Pepsi@pepsico.com",
  "phone_number": "2346281"

}


###
#show
GET http://localhost:3000/suppliers/5
Content-Type: application/json

###
#index
GET http://localhost:3000/suppliers/
Content-Type: application/json

###
#update 
PATCH http://localhost:3000/suppliers/
Content-Type: application/json

{

  "name":"SterlingFoodsInc",
  "email":"sterlingfoods.inc@gmail.com",
  "phone_number":"9538899"

}

###
#delete
DELETE http://localhost:3000/suppliers/3
Content-Type: application/json