@domain = http://localhost:3000
@jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoyLCJleHAiOjE2NDMzMTAwMDR9.lG52lGIiaMOMMKUqEBvND_Bu2yEGBUagr1LWrxzbn4o

Get http://localhost:3000/products/
Content-Type: application/json
#broken #index


###

POST http://localhost:3000/products
Content-Type: application/json
#works #create 

{
  "name": "Soup",
  "price": "4",
  "ingredients": "Ask about soup of the day."
}

#works


###

GET http://localhost:3000/products/1
Content-Type: application/json
#works (product by id) show


###

PATCH http://localhost:3000/products/1
Content-Type: application/json

 {
   "name":"",
   "ingredients":"",
   "price"""

 }

#works(update) 

###

DELETE http://localhost:3000/products/2
Content-Type: application/json
#works #destroy



#### Begin supplier requests

#create
POST http://localhost:3000/suppliers
Content-Type: application/json

{

  "name": "Pepsi",
  "email": "Pepsi@pepsico.com",
  "phone_number": "2346281"

}


###
#show
GET http://localhost:3000/suppliers/5
Content-Type: application/json

###
#index
GET http://localhost:3000/suppliers/
Content-Type: application/json

###
#update 
PATCH http://localhost:3000/suppliers/
Content-Type: application/json

{

  "name":"SterlingFoodsInc",
  "email":"sterlingfoods.inc@gmail.com",
  "phone_number":"9538899"

}

###
#delete
DELETE http://localhost:3000/suppliers/3
Content-Type: application/json


###
#begin user creation with password
POST http://localhost:3000/users
Content-Type: application/json

  {

  "name": "Ralph",
  "email": "Ralph@gmail.com",
  "password": "password",
  "password_confirmation": "password"

  }

###
#begin sessions login#####

POST http://localhost:3000/sessions
Content-Type: application/json

  {

    "email": "Jane@gmail.com",
    "password": "password"

  }


###
#index 
GET http://localhost:3000/users
Content-Type: application/json

###
# create order request
POST http://localhost:3000/orders
Content-Type: application/json
Authorization: Bearer {{ jwt }}

 {
   
   "product_id": ,
   "quantity": 1,
   "tax": 0.89,
   "subtotal": 12,
   "total": 12.89
   


 }

###
#show order request
Get http://localhost:3000/orders/1
Content-Type: application/json
Authorization: Bearer {{ jwt }}

###
#index 
Get http://localhost:3000/orders
Authorization: Bearer {{ jwt }}

###

